apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pureSecret.name }}
  namespace: {{ .Values.pureSecret.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.syncWave }}"
  labels:
    app.kubernetes.io/name: portworx
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  {{ .Values.pureSecret.dataFileName }}: {{ .Values.pureSecret.data | b64enc }}

