pureSecret:
  name: px-pure-secret
  namespace: portworx
  dataFileName: pure.json
  data: |
    {
      "FlashArrays": [
        {
          "MgmtEndPoint": "ph531-a41.dev.storage.com",
          "APIToken": "abc"
        }
      ]
    }

# Argo CD
syncWave: "1"

